#!/usr/bin/env bash
clear && sleep 4 && \
# Only upgrade when on device so that /boot can be updated & upgraded.
# Note that pi /boot dir doesn't get mounted the same in the emulator compared to the device
echo " Running provision for device environment "
sleep 2 && \
apt-get update && apt-get -f install -y && apt-get upgrade -y && apt-get -f install -y && \
#@ Needs to be orig /boot -> do from qbian ??
echo "Editing /boot/config.txt - note device is required" && \
echo -e "dtparam=i2c1=on\ndtparam=i2c_arm=on\ndevice_tree=" >> /boot/config.txt && \
## rpi-serial
git clone https://github.com/lurch/rpi-serial-console.git && \
/root/rpi-serial-console/rpi-serial-console disable && \
## install dockerui & start in daemon mode
## Installer docker
curl -sSL -o docker-hypriot_1.8.2-1_armhf.deb http://downloads.hypriot.com/docker-hypriot_1.8.2-1_armhf.deb && \
dpkg -i docker-hypriot_1.8.2-1_armhf.deb && \
gpasswd -a $user docker && \
service docker start && \
echo "Complete Device Provisions : Please reboot"

#
#
# Put in init ?
# docker pull hypriot/rpi-dockerui && \
# docker run -d -p 9000:9000 --privileged --name qbian-docker-ui-init -v /var/run/docker.sock:/var/run/docker.sock hypriot/rpi-dockerui && \
